-- Documentos e termos anexados aos equipamentos por esta aplicação (fora do GLPI).
-- O equipamento é referenciado pelo tipo e id do GLPI; o GLPI continua dono do cadastro do equipamento.
-- SQL portável: roda em PostgreSQL (servidor) e em H2 modo PostgreSQL (perfil local e testes).
CREATE TABLE documento_equipamento (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_item         VARCHAR(40)   NOT NULL,  -- itemtype do GLPI (Computer; no futuro Monitor, Printer...)
    item_id           BIGINT        NOT NULL,  -- id do equipamento no GLPI
    item_nome         VARCHAR(255),            -- nome do equipamento no envio (ajuda a achar se for renomeado)
    categoria         VARCHAR(40)   NOT NULL,  -- CategoriaDocumento
    titulo            VARCHAR(255)  NOT NULL,
    observacao        VARCHAR(2000),
    validade          DATE,                    -- garantia, contrato ou termo com prazo (opcional)
    nome_arquivo      VARCHAR(255)  NOT NULL,  -- nome original do arquivo enviado
    tipo_conteudo     VARCHAR(120)  NOT NULL,
    tamanho_bytes     BIGINT        NOT NULL,
    sha256            VARCHAR(64)   NOT NULL,  -- integridade: prova que o arquivo guardado é o enviado
    caminho           VARCHAR(500)  NOT NULL,  -- relativo à pasta de armazenamento (inventario.documentos.pasta)
    responsavel_id    BIGINT,                  -- responsável (Usuário) no GLPI no momento do envio:
    responsavel_nome  VARCHAR(255),            --   num termo, é quem assinou, mesmo que depois mude
    enviado_por_id    BIGINT        NOT NULL,  -- técnico logado (usuário do GLPI)
    enviado_por_nome  VARCHAR(255)  NOT NULL,
    enviado_em        TIMESTAMP     NOT NULL,
    removido_em       TIMESTAMP,               -- remoção é lógica: termo é registro, o arquivo fica guardado
    removido_por_nome VARCHAR(255),
    motivo_remocao    VARCHAR(500)
);

CREATE INDEX idx_documento_equipamento_item ON documento_equipamento (tipo_item, item_id);
CREATE INDEX idx_documento_equipamento_categoria ON documento_equipamento (categoria);
